poetry.lock
- Any file can be included with the pymdowm-snippets extension. Patched 10.0
- Unintended leak of Proxy-Authorization header in requests. Patched requests 2.31
=> Update poetry.lock for Security updates

.github/workflows/ci_pr.yml, README.md, dbterd/adapters/base.py, dbterd/cli/params.py, dbterd/helpers/file.py, docs/index.md, docs/nav/guide/cli-references.md, poetry.lock, pyproject.toml, tests/unit/adapters/test_base.py, tests/unit/helpers/test_file.py
resolves #45 
- Make top pin to <1.0.0
- Add WARN to upgrade the package for new artifact version which not supported yet
- Add `-cv` catalog version option
=> feat: soft deps + catalog option 

dbterd/adapters/algos/base.py, dbterd/adapters/algos/test_relationship.py, dbterd/adapters/filter.py, dbterd/adapters/meta.py, dbterd/cli/params.py, docs/nav/guide/cli-references.md, tests/unit/adapters/algos/test_test_relationship.py, tests/unit/adapters/targets/d2/test_d2_test_relationship.py, tests/unit/adapters/targets/dbml/test_dbml_test_relationship.py, tests/unit/adapters/targets/graphviz/test_graphviz_test_relationship.py, tests/unit/adapters/targets/mermaid/test_mermaid_test_relationship.py, tests/unit/adapters/targets/plantuml/test_plantuml_test_relationship.py, tests/unit/adapters/test_filter.py
resolves #54 
Add `--entity-name-format` (`-enf` in short) to decide how the table name is generated
Currently, it supports
```
dbterd run --entity-name-format resource.package.model # default
dbterd run --entity-name-format database.schema.table # with fqn of the physical tables
dbterd run --entity-name-format schema.table # with schema.table only
dbterd run --entity-name-format table # with table name only
```
=> Feature/54 Add entity name format

poetry.lock
resolves https://github.com/datnguye/dbterd/security/dependabot/7
=> chore: `Cookie` HTTP header isn't stripped on cross-origin redirects

dbterd/adapters/algos/test_relationship.py
resolves #
Not sure if there is an existing logged issue for this, however:
This is a fix to an error I get with my manifest.json using dbt-core 1.6.6 and snowflake-adapter 1.6.4. Possibly due to dynamic tables or quoted columns I couldn't quite work it out
```
File "/dbterd/adapters/algos/test_relationship.py", line 170, in get_table_map
if f'("{map[1].split(".")[-1]}")'.lower() in to_model.replace("'", '"').lower():
IndexError: list index out of range
```
=> Checked map length to prevent errors

dbterd/adapters/adapter.py, dbterd/adapters/algos/base.py, dbterd/adapters/meta.py, dbterd/adapters/targets/dbml/dbml_test_relationship.py, pyproject.toml, tests/unit/adapters/algos/test_test_relationship.py, tests/unit/adapters/targets/dbml/test_dbml_test_relationship.py
resolves #65 
Add table's note for DBML target from model's description field
=> feat: add dbml table note

dbterd/adapters/dbt_cloud.py, dbterd/cli/params.py, docs/nav/guide/dbt-cloud/download-artifact-from-a-job-run.md, docs/nav/guide/dbt-cloud/download-artifact-from-a-job.md, mkdocs.yml, tests/unit/adapters/test_dbt_cloud.py
another option to #63 
Download the latest artifacts from a Job ID with new option `--dbt-cloud-job-id`
=> feat: download artifacts from Job ID

dbterd/adapters/filter.py, tests/unit/adapters/test_filter.py
resolves https://github.com/datnguye/dbterd/issues/73
Fixed a bug that prevented ER diagrams from being output when data source table names were capitalized. This is because the `rule` part is `lower()`, but `lower` is not applied in the `is_satisfied_by_exact` function. Therefore, the result of the `is_selected_table` function was determined to be false, and the ER diagram was not output as expected.
- https://github.com/datnguye/dbterd/blob/main/dbterd/adapters/filter.py#L77
=> Lowercase node_name in comparison to match even if it is uppercase

dbterd/adapters/targets/mermaid/mermaid_test_relationship.py, dbterd/cli/params.py, docs/nav/guide/cli-references.md, tests/unit/adapters/targets/mermaid/test_mermaid_test_relationship.py
resolves https://github.com/datnguye/dbterd/issues/78
I added `--omit_columns` option to omit columns from diagrams when the output format is mermaid.
I thought about omitting columns for `--target` other than mermaid, but since dbml, for example, requires at least one column, I decided to support only `--target = mermaid`.
=> Add `omit_columns` option to mermaid

dbterd/adapters/algos/test_relationship.py
resolves https://github.com/datnguye/dbterd/issues/80
Ensure ordering of tables and relationships. This will allow CI/CD to suppress unnecessary differential output when automatically generating documents.
=> Ensure ordering of tables and relationship

dbterd/adapters/targets/mermaid/mermaid_test_relationship.py, tests/unit/adapters/targets/mermaid/test_mermaid_test_relationship.py
resolves https://github.com/datnguye/dbterd/issues/81
Mermaid may not be able to render special characters. To deal with such cases, we have made changes to replace or omit special characters.
=> Replace special symbol characters with other characters to allow them to be drawn as mermaid

dbterd/adapters/algos/base.py, tests/unit/adapters/algos/test_test_relationship.py
resolves https://github.com/datnguye/dbterd/issues/88
This modification allows a diagram to be drawn even if it has the following recursive relationship.
```mermaid
erDiagram
"MY_PROJECT.CATEGORY" {
}
"MY_PROJECT.CATEGORY" }|--|| "MY_PROJECT.CATEGORY": categoryid--parentCategoryId
```
=> Allows drawing recursive relationships

dbterd/adapters/algos/base.py, tests/unit/adapters/algos/test_test_relationship.py
resolves #87 
- Handling metadata catalog null
- Supporting Self-relationship with 1 parent model
=> fix: handling metadata catalog null & self rel

dbterd/adapters/algos/base.py, dbterd/adapters/algos/test_relationship.py, dbterd/default.py
resolves #92 
Fix `dbt run-metadata` to handle probably the `-enf` option
=> fix: run metadata need handle entity name format probably

poetry.lock, pyproject.toml
resolves #96 
- Add `requests` deps
=> fix: add requests as deps

dbterd/adapters/dbt_core/dbt_invocation.py, tests/unit/adapters/test_dbt_invocation.py
Let's dbterd work independently without installing dbt-core
=> chore: decouple dbt-core as an ext deps

dbterd/adapters/base.py, dbterd/adapters/targets/d2/d2_test_relationship.py, dbterd/adapters/targets/dbml/dbml_test_relationship.py, dbterd/adapters/targets/graphviz/graphviz_test_relationship.py, dbterd/adapters/targets/mermaid/mermaid_test_relationship.py, dbterd/adapters/targets/plantuml/plantuml_test_relationship.py, dbterd/cli/params.py, docs/nav/guide/cli-references.md, tests/unit/cli/test_runner.py
resolves #97 
Add `--output-file-name` (`-ofn`) option to customize the output file name
=> feat: add --output-file-name option

dbterd/adapters/algos/base.py, dbterd/adapters/algos/test_relationship.py, dbterd/adapters/base.py, dbterd/adapters/targets/constants.py, dbterd/adapters/targets/d2.py, dbterd/adapters/targets/d2/__init__.py, dbterd/adapters/targets/dbml.py, dbterd/adapters/targets/dbml/__init__.py, dbterd/adapters/targets/default.py, dbterd/adapters/targets/graphviz.py, dbterd/adapters/targets/graphviz/__init__.py, dbterd/adapters/targets/mermaid.py, dbterd/adapters/targets/mermaid/__init__.py, dbterd/adapters/targets/plantuml.py, dbterd/adapters/targets/plantuml/__init__.py, pyproject.toml, tests/unit/adapters/targets/d2/test_d2_test_relationship.py, tests/unit/adapters/targets/dbml/test_dbml_test_relationship.py, tests/unit/adapters/targets/graphviz/test_graphviz_test_relationship.py, tests/unit/adapters/targets/mermaid/test_mermaid_test_relationship.py, tests/unit/adapters/targets/plantuml/test_plantuml_test_relationship.py, tests/unit/adapters/test_base.py, tests/unit/cli/test_runner.py
related to #95 
Support to easily add new (standalone) algo module
=> refactor: support dynamic algo module

dbterd/adapters/algos/test_relationship.py, tests/unit/adapters/algos/test_test_relationship.py
`find_related_nodes_by_id` shouldn't raise exception but returns the input right away when type is not supported yet
=> feat(api): `find_related_nodes_by_id` shouldn't raise exception

dbterd/adapters/algos/base.py, poetry.lock, tests/unit/adapters/algos/test_test_relationship.py
=> fix: select exposure not working for run-metadata

dbterd/adapters/targets/mermaid.py, tests/unit/adapters/targets/mermaid/test_mermaid_column_types.py
Previously, from a complex nested type like `a<b<c d, e f>>`, the mermaid adapter would ignore `a` and capture `b`, `c d` and `, e f`.
Now it captures `a` and `b<c d, e f>`, which is discarded as far as I can see.
I've simplified the regex expression and tested with the obvious cases, but I'm not sure if the new regex might miss some edge cases. It'd be nice to add more tests if you think I might be missing something :) 
I'm pushing twice, without the fix implemented and then with the fix, ~~so that you can see the testing logs in both cases.~~ well workflow needs approval anyway 😅 
Thanks for your work!
=> fix: mermaid complex types
